version: "3.5"
services:
  vulnsqlapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./static:/root/
  postgresdb:
    image: postgres:14
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_db_password
      - POSTGRES_TRUST_LOCALNET=true
    secrets:
      - postgres_db_password
    volumes:
      - ./test-data.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
secrets:
  postgres_db_password:
    file: ./secrets/postgress_db_password
